name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install sympy

      - name: Run tests for code/test_LIC_check.py
        run: pytest code/test_LIC_check.py

      - name: Run tests for code/test_decide.py
        run: pytest code/test_decide.py
